### ISSUE TITLE
Right-clicking a cauldron block crashes the game

### ISSUE THREAD

**Issue by apace100** [apace100/origins-classes#39]
Not sure rn whether this just applies to clerics or to everyone - either way: it's buggy
Something about the block state property not existing on minecraft:lava_cauldron

**Comment by Withersip** [comment]
happens to me too, only happened when i was a cleric class

**Comment by echohunter221** [comment]
It's only the cleric, can confirm. Client only crash as well, crash log in [pastebin](https://pastebin.com/byaGjQNT)

**Comment by AzureMonument** [comment]
Okay, so people already found this. I'll post my [pastebin](https://pastebin.com/vuJKCh9x) as well.
More specifically, I crashed when trying to fill the cauldron with a water bucket. Don't know if it applies to filled cauldrons.

**Comment by FluffyDiscord** [comment]
clicking on a cauldron with a right hand, empty or not, crashes the game

**Comment by Nebulava** [comment]
I've found I'm able to extend potions still, as long as they're regular potions, not splash or anything. My workaround rn is asking someone else to fill it, or letting the rain fill it. Filling it myself or otherwise rightclicking with anything else will crash my client.

Edit: New info? It seems to always crash when the water level is at stage 1 (lowest water amount). Just tried extending 3 of the same potions in a row on a full cauldron. The first two succeeded, but the last one crashed. My splash potion test earlier also crashed at cauldron stage 1. An interesting bug for sure.

**Comment by FluffyDiscord** [comment]
the worst thing about this is, that this repo seems like is using old libraries which are unavailable, so we can't event help fix it, because noone can run the setup script

**Comment by VaelophisNyx** [comment]
> Not sure rn whether this just applies to clerics or to everyone - either way: it's buggy
> Something about the block state property not existing on minecraft:lava_cauldron

Just Clerics. Offering my confirmation, and a crash report
[latest (2).log](https://github.com/apace100/origins-classes/files/6721538/latest.2.log)


this is from an empty cauldron, to a full cauldron with a water bucket. Normal function for all classes but Cleric.

**Comment by apace100** [comment]
Fixed in 1.2.2
